name: Run Unit, Integration, and System Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

    - name: Run Unit, Integration, and System Tests
      run: mvn test -Dtest=es.codeurjc.web.nitflex.unit.**,es.codeurjc.web.nitflex.integration.**,es.codeurjc.web.nitflex.e2e.web.**
